# === ПУТИ К ФАЙЛАМ ===
data_file: "Фонд_Новопорт.xlsx"  # содержит путь к исходному файлу с данными

# === ОПЦИИ ДЛЯ РАСЧЕТА РЕГУЛЯРНОЙ СЕТКИ ОХВАТА ВСЕХ ФОНДОВ ===
option_percent: да  # учет заданного процента скважин фонда для включения в программу ГДИС для 2 сценария
list_order_fond: доб, наг, пьез  # список фондов в порядке построения из них регулярной сетки скважин
percent_piez: 25  # процент пьезометрических скважин в программе ГДИС
percent_inj: 25  # процент нагнетательных скважин в программе ГДИС
percent_prod: 20  # процент добывающих скважин в программе ГДИС

# === ОПЦИИ ДЛЯ РАСЧЕТА СЕТКИ ОПТИМАЛЬНОГО ОХВАТА ДОБЫВАЮЩЕГО ФОНДА ===
separation_by_years: 2  # распределение по годам скважин в "слепых" зонах

# === ОПЦИИ ДЛЯ РАСЧЕТА  ===
calculation_scenario: regular  # определяется сценарий расчета модуля (регулярная сеть или оптимальный охват добывающих)
gdis_option: 01.02.2022  # 'ДД.ММ.ГГГГ'
calc_option: True  # определяет критерий учета процента длины ГС для попадания в зону охвата
percent: 70  # процент длины ГС для включения в зону охвата
horizon_count:   # определяет максимальное кол-во объектов для скважины

# === ОСНОВНЫЕ ПАРАМЕТРЫ ===
mult_coef: 1, 1.5, 2, 2.5  # список коэффициентов увеличения радиуса исследования
limit_radius_coef: 1.5  # ограничение на коэффициент увеличения радиуса исследования
min_length_horWell: 150  # минимальная длина ствола горизонтальной скважины (для выгрузки NGT)
water_cut: 90  # %, скважины с меньшим процентом обводненности не будет включена в ОС
fluid_rate:  #  м3/сут, скважины с дебитом жидкости выше указанного не включаются в ОС
mean_oilrate_option: нет  # отбрасывать добывающие скважины с дебитом больше заданного процента от среднего дебита по объекту
percent_oilrate: 100  # % от среднего дебита по объекту
limit_oilrate:  # т/сут, ограничение на дебит добывающих скважин
limit_research_time: нет  # параметр отвечающий за учет границ времени исследования в зависимости от типа скважины (да/нет)
min_research_time: 5 #  минимальное время исследования ННС (для ГС в 2 раза больше)
max_research_time: 15 #  максимальное время исследования ННС (для ГС в 2 раза больше)


# === РАСЧЕТ ОПТИМАЛЬНОГО РАДИУСА ОХВАТА ===
max_distance: 300  # максимальный радиус для выделения скважин первого окружения
verticalWellAngle: 10  # зона вертикальных скважин в полярной системе координат
MaxOverlapPercent: 20  # максимальный процент перекрытия от общей длины скважины
angle_horizontalT1: 10  # угол расширения сектора T1 ГС
angle_horizontalT3: 10  # угол расширения сектора T3 ГС
