from PyQt6 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.frame)
        self.treeWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMouseTracking(True)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.treeWidget.setLineWidth(2)
        self.treeWidget.setMidLineWidth(2)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.treeWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setAllColumnsShowFocus(False)
        self.treeWidget.setWordWrap(False)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setExpandsOnDoubleClick(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(260)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(260)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.gridLayout_4.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.qframe = QtWidgets.QFrame(parent=self.frame)
        self.qframe.setObjectName("qframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.qframe)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calculate = QtWidgets.QPushButton(parent=self.qframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.calculate.sizePolicy().hasHeightForWidth())
        self.calculate.setSizePolicy(sizePolicy)
        self.calculate.setStyleSheet("")
        self.calculate.setObjectName("calculate")
        self.verticalLayout_2.addWidget(self.calculate)
        self.gridLayout_4.addWidget(self.qframe, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.path_result_db = QtWidgets.QLineEdit(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(18)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_result_db.sizePolicy().hasHeightForWidth())
        self.path_result_db.setSizePolicy(sizePolicy)
        self.path_result_db.setText("")
        self.path_result_db.setCursorPosition(0)
        self.path_result_db.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.path_result_db.setObjectName("path_result_db")
        self.horizontalLayout_4.addWidget(self.path_result_db)
        self.choose_directory = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_directory.sizePolicy().hasHeightForWidth())
        self.choose_directory.setSizePolicy(sizePolicy)
        self.choose_directory.setMaximumSize(QtCore.QSize(30, 16777215))
        self.choose_directory.setObjectName("choose_directory")
        self.horizontalLayout_4.addWidget(self.choose_directory)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.combobox_scenario = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_scenario.sizePolicy().hasHeightForWidth())
        self.combobox_scenario.setSizePolicy(sizePolicy)
        self.combobox_scenario.setObjectName("combobox_scenario")
        self.horizontalLayout_5.addWidget(self.combobox_scenario)
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.combobox_horizon = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_horizon.sizePolicy().hasHeightForWidth())
        self.combobox_horizon.setSizePolicy(sizePolicy)
        self.combobox_horizon.setObjectName("combobox_horizon")
        self.horizontalLayout_5.addWidget(self.combobox_horizon)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.report = QtWidgets.QTableView(parent=self.tab_3)
        self.report.setObjectName("report")
        self.gridLayout_3.addWidget(self.report, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.save_all_tables = QtWidgets.QPushButton(parent=self.tab_3)
        self.save_all_tables.setObjectName("save_all_tables")
        self.save_all_filtered_tables = QtWidgets.QPushButton(parent=self.tab_3)
        self.save_all_filtered_tables.setObjectName("save_all_filtered_tables")
        self.horizontalLayout_3.addWidget(self.save_all_tables)
        self.horizontalLayout_3.addWidget(self.save_all_filtered_tables)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.results_layout = QtWidgets.QVBoxLayout()
        self.results_layout.setObjectName("results_layout")
        self.results = QtWidgets.QTableView(parent=self.tab)
        self.results.setObjectName("results")
        self.results_layout.addWidget(self.results)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_table = QtWidgets.QPushButton(parent=self.tab)
        self.save_table.setObjectName("save_table")
        self.horizontalLayout_2.addWidget(self.save_table)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.results_layout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.results_layout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(parent=self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_project = QtGui.QAction(parent=MainWindow)
        self.new_project.setObjectName("new_project")
        self.open_project = QtGui.QAction(parent=MainWindow)
        self.open_project.setObjectName("open_project")
        self.saveproject = QtGui.QAction(parent=MainWindow)
        self.saveproject.setObjectName("saveproject")
        self.exit = QtGui.QAction(parent=MainWindow)
        self.exit.setObjectName("exit")
        self.action_5 = QtGui.QAction(parent=MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtGui.QAction(parent=MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtGui.QAction(parent=MainWindow)
        self.action_7.setObjectName("action_7")
        self.readme_txt = QtGui.QAction(parent=MainWindow)
        self.readme_txt.setObjectName("readme_txt")
        self.reference = QtGui.QAction(parent=MainWindow)
        self.reference.setObjectName("reference")
        self.menu.addAction(self.open_project)
        self.menu_3.addAction(self.readme_txt)
        self.menu_3.addAction(self.reference)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Параметр"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Значение"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Файл с данными"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Опции расчета"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Сценарий расчета"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Дата последнего ГДИС"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Критерий охвата траектории ГС"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "% охвата длины ГС для исслед-я"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("MainWindow", "Макс. кол-во объектов скважины"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Основные параметры"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Список коэф-ов"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Огран-е коэф-та на R"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Мин. длина ГС (для NGT Smart)"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "Обводненность, %"))
        self.treeWidget.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "Дебит жидкости, м3/сут"))
        self.treeWidget.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "Учет Q ср. по объекту"))
        self.treeWidget.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "% от Q ср. по объекту"))
        self.treeWidget.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "Огран-е на дебит нефти, т/сут"))
        self.treeWidget.topLevelItem(2).child(8).setText(0, _translate("MainWindow", "Учет границ исслед. ННС/ГС"))
        self.treeWidget.topLevelItem(2).child(9).setText(0, _translate("MainWindow", "Мин. время исслед. ННС, сут"))
        self.treeWidget.topLevelItem(2).child(10).setText(0, _translate("MainWindow", "Макс. время исслед. ННС, сут"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Регулярная сетка для всех фондов"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Учет % от каждого фонда"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Порядок фондов для ГДИС"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "% пьезометрических скважин"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "% нагнетательных скважин"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "% добывающих скважин"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Оптим. охват добывающего фонда"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Распред-ие ГДИС скв. по годам"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Первый ряд окружения"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Макс. радиус, м"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Сектор для ННС в ПСК, град"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "Ограничение по % перекрытия"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "Сектор для T1 ГС в ПСК, град"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "Сектор для T3 ГС в ПСК, град"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.calculate.setText(_translate("MainWindow", "Рассчитать и сохранить"))
        self.label_2.setText(_translate("MainWindow", "Сохранение результатов: "))
        self.choose_directory.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Сценарий расчета:"))
        self.label.setText(_translate("MainWindow", "Объект расчета:"))
        self.save_all_tables.setText(_translate("MainWindow", "Сохранить все сценарии в Excel"))
        self.save_all_filtered_tables.setText(_translate("MainWindow", "Сохранить все сценарии по текущему объекту"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Сводка по результатам"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Визуализация"))
        self.save_table.setText(_translate("MainWindow", "Сохранить текущую таблицу в Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Таблица опорной сетки"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_3.setTitle(_translate("MainWindow", "Помощь"))
        self.new_project.setText(_translate("MainWindow", "Новый"))
        self.open_project.setText(_translate("MainWindow", "Загрузить..."))
        self.readme_txt.setText(_translate("MainWindow", "Краткая инструкция"))
        self.reference.setText(_translate("MainWindow", "Руководство пользователя"))
